"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var dispatchers_1 = require("./blocks/helpers/dispatchers");
exports.fetchBlock = dispatchers_1.fetchBlock;
var dispatchers_2 = require("./contracts/helpers/dispatchers");
exports.removeContractInstance = dispatchers_2.removeContractInstance;
exports.loadContractInstance = dispatchers_2.loadContractInstance;
exports.removeContractSpec = dispatchers_2.removeContractSpec;
exports.loadContractSpec = dispatchers_2.loadContractSpec;
var dispatchers_3 = require("./txs/helpers/dispatchers");
exports.sendTransaction = dispatchers_3.sendTransaction;
exports.removeTransaction = dispatchers_3.removeTransaction;
exports.addTransaction = dispatchers_3.addTransaction;
exports.followTransaction = dispatchers_3.followTransaction;
var dispatchers_4 = require("./vtxconfig/helpers/dispatchers");
exports.setWeb3 = dispatchers_4.setWeb3;
exports.init = dispatchers_4.init;
exports.reset = dispatchers_4.reset;
exports.start = dispatchers_4.start;
var dispatchers_5 = require("./accounts/helpers/dispatchers");
exports.removeAccount = dispatchers_5.removeAccount;
exports.addAccount = dispatchers_5.addAccount;
